### ISSUE TITLE
Change API gateway error messages and urls (e.g. contact url) before CAMPD release

### ISSUE THREAD

**Issue by j-tafoya** [USEPA/cam-api-portal#107]
Determine what we will put in the API gateway error messages and add the CAM API Contact form URL.

**Comment by j-tafoya** [comment]
Contact url: https://www.epa.gov/airmarkets/forms/cam-api-contact-form
Signup url: https://www.epa.gov/airmarkets/cam-api-portal

**Comment by j-tafoya** [comment]
New url for contact us form:  https://www.epa.gov/airmarkets/forms/cam-api-contact-us

**Comment by ibarra-michelle** [comment]
@j-tafoya could you review the Contact Us and Sign up urls for the beta and (future) prod API Backends?

**Comment by ibarra-michelle** [comment]
Reviewed and approved by @j-tafoya.
