### ISSUE TITLE
Create demo scripts in Python and R that shows how to use the Bulk Data API

### ISSUE THREAD

**Issue by maheese** [USEPA/cam-api-portal#120]
This will be needed for CAMPD 1.1 when the FTP service is taken down.  Currently, there are users that have created programs that crawl the FTP site and download files directly.  The project should be in the USEPA GitHub org and contain a README and demo code that explains how this can be accomplished in the new CAMPD with the CAM APIs.  CAMPD and the CAM-API-Portal can link to this repo from their resources page.

**Comment by kstetsyuk** [comment]
@j-tafoya ready for review https://github.com/USEPA/cam-api-examples

**Comment by ibarra-michelle** [comment]
Added my suggestions in this PR: https://github.com/USEPA/cam-api-examples/pull/3
