### ISSUE TITLE
Fix the Contact Us button in the MVP so it collapses into the single column in the mobile view

### ISSUE THREAD

**Issue by maheese** [USEPA/cam-api-portal#121]

**Comment by maheese** [comment]
@ntknguyen one minor request, can you add a little bit of spacing after the button (margin-bottom-1) so its not right on top of the text when you are on a phone size screen?

**Comment by ntknguyen** [comment]
> @ntknguyen one minor request, can you add a little bit of spacing after the button (margin-bottom-1) so its not right on top of the text when you are on a phone size screen?

It's fixed.

**Comment by maheese** [comment]
@ntknguyen looks great. Thanks!
