### ISSUE TITLE
Investigate fixing the description in the swagger json in the re-engineering

### ISSUE THREAD

**Issue by ntknguyen** [USEPA/cam-api-portal#123]

**Comment by j-tafoya** [comment]
The title and description is fed into the swagger doc via this [bootstrap.js file](https://github.com/US-EPA-CAMD/easey-common/blob/master/src/nestjs/bootstrap.ts) in the devops repo. The title and description are set via the manifest-vars.yml files in each API repo or if not set there, then it's set in the app.config.ts file. Within the bootstrap.js file, the custom description and custom css for the description is only set if it is not the production environment. Thus, we may be able to set the description in the manifest-vars file for production for each API and have it populate in the swagger doc if we modify the bootstrap.js file to pull in the description from the config service like it does for the tile etc.
