### ISSUE TITLE
Add first FAQ to the FAQ page

### ISSUE THREAD

**Issue by j-tafoya** [USEPA/cam-api-portal#148]

**Comment by sgillEPA** [comment]
Content for the first FAQ
Are there any restrictions on how the API can be used?
We are using default rate limits of 1000 requests per hour. In addition to the rate limit there is a 15 minute timeout on any API request and also any of the endpoints that support paging are limited to 25,000 rows per page. Finally, the UI limits downloads from the streaming services to 1,000,000 records but there is no limit on the streaming services APIs (other than the timeout).
