### ISSUE TITLE
Draft what's new content for CAMPD 1.1 release

### ISSUE THREAD

**Issue by j-tafoya** [USEPA/cam-api-portal#166]

**Comment by kstetsyuk** [comment]
@j-tafoya 
Messaging can be (unless there are any concerns):
The Clean Air Markets Program Data (CAMPD) 1.1 has been released! Click [here](https://campd.epa.gov/) to check it out!

I went ahead and made a [branch](166-what's-new-for-campd-1.1) for this new info box too.
