### ISSUE TITLE
Create a Drupal Sandbox and/or unpublished production area for our development work

### ISSUE THREAD

**Issue by j-tafoya** [USEPA/cam-api-portal#2]
* Figure out what access is needed
* Determine web area
* Demo drupal cms
* Possible password/hidden mode on production?

**Comment by sgillEPA** [comment]
From Kevin:

Sorry to be the bearer of bad news, but unfortunately we do not have a sandbox server for the new Drupal system. We had a sandbox server on the previous Drupal system, but OWC has not yet created one for the new Drupal 9 environment.

From the WebCMS FAQs – “There will also be a rarely updated stage environment (used mostly for scanning production-ready code), and a dev environment for testing the newest code (updated daily).  They are not set up yet.” 

I’m not aware of any timeline that OWC has given for this.

In the meantime, I would suggest working with drafts on the production Drupal. I know this isn’t ideal for testing, but it’s the best/only option we have for now!

**Comment by sgillEPA** [comment]
From Kevin:

"Sorry to be the bearer of bad news, but unfortunately we do not have a sandbox server for the new Drupal system. We had a sandbox server on the previous Drupal system, but OWC has not yet created one for the new Drupal 9 environment.

From the WebCMS FAQs – “There will also be a rarely updated stage environment (used mostly for scanning production-ready code), and a dev environment for testing the newest code (updated daily).  They are not set up yet.” 

I’m not aware of any timeline that OWC has given for this.

In the meantime, I would suggest working with drafts on the production Drupal. I know this isn’t ideal for testing, but it’s the best/only option we have for now!"

**Comment by sgillEPA** [comment]
"I know that Drupal drafts are not always ideal for testing/review. For the Progress Reports, I was able to work with some GDIT contractors to set up a W3 server to house a “development” version of the progress report. When you’re on the VPN, you can access it by going to pine.customs.epa.gov/reports. Would something like that work for your testing?

One other option, you could request a “shield” where a user would log in with a generic username and password on their browser to access a “published” drupal page. This allows for testing of a “published” page on Drupal without actually releasing it to the public."

**Comment by sgillEPA** [comment]
Local environment -> cloud.gov -> shielded environment

**Comment by sgillEPA** [comment]
@sgillEPA to reach out to Travis Johnson about shielded page

**Comment by sgillEPA** [comment]
For a shielded page, we need to submit a [form](https://www.epa.gov/webcmstraining/forms/request-shield-external-review) once we are ready for review.

**Comment by ntknguyen** [comment]
[Draft page](https://www.epa.gov/airmarkets/cam-api-portal) for reviewing.

**Comment by ntknguyen** [comment]
From Lisa Cameron, Web CMS Supports, 
"You can work on staging as well
https://stage-www.epa.gov/saml/login
But the pages are not viewable on the public side when published.

There’s not a schedule when the staging server is updated, it happens on occasion. When there is an update, pages created on staging are deleted. 
There are no notifications on staging, it’s for practice purposes only, not for long term development.

Staging is used only for testing purposes, the pages you create there are not permanent. If this concerns you, then working on production is the best choice.

This guideline will explain about password protected pages, https://www.epa.gov/webcmsltraining/forms/request-shield-external-review."
