### ISSUE TITLE
Modify index.html page to only contain the app outside drupal

### ISSUE THREAD

**Issue by j-tafoya** [USEPA/cam-api-portal#28]
The create-create-app scripts generate multiple files that we need to place in one html document for the Drupal environment. 

- [x] Generate an html template with the necessary tags 
- [x] Test pasting in the generated js and css to this template and create a draft in Drupal
- [x] Create etc folder at the top level
- [x] Create drupal-template.html file with scripts and css

**Comment by ibarra-michelle** [comment]
@j-tafoya - this PR is ready for review 🔍
