### ISSUE TITLE
Collab with Travis L to see how CAMD webpages will be updated to link to CAM API

### ISSUE THREAD

**Issue by j-tafoya** [USEPA/cam-api-portal#44]
- [ ] Modifications to [data resources page](https://www.epa.gov/airmarkets/data-resources)
- [ ] Modifications to [power sector data page](https://www.epa.gov/airmarkets/power-sector-emissions-data)
- [ ] Possibly link to CAM API portal from [re-engineering FAQ](https://www.epa.gov/airmarkets/frequent-questions-about-camd-re-engineering-effort)

**Comment by kstetsyuk** [comment]
Have some MOB meetings with Travis that I can use to discuss this.

**Comment by kstetsyuk** [comment]
I think at this point, it'd be good to figure what we'd like to see in the webpages. Travis identified these pages that need to be updated for CAMPD info:

[https://www.epa.gov/airmarkets/data-resources]
1. [https://www.epa.gov/airmarkets/facility-attributes]
2. [https://www.epa.gov/airmarkets/power-plant-emission-trends]
3. [https://www.epa.gov/airmarkets/facility-level-comparisons]
4. [https://www.epa.gov/airmarkets/power-plant-data-viewer#Instructions]
5. [https://www.epa.gov/airmarkets/allowance-data]
6. [https://www.epa.gov/airmarkets/power-sector-emissions-data]
[https://www.epa.gov/csapr]
[https://www.epa.gov/airmarkets/basic-information-site-map]
[https://www.epa.gov/airmarkets] (Banner - image 2)
FAQs
1. [https://www.epa.gov/airmarkets/camds-power-sector-emissions-data-faqs]
2. [https://www.epa.gov/airmarkets/allowance-faqs]
What is emissions trading?
1. [https://www.epa.gov/emissions-trading-resources/what-emissions-trading]
