### ISSUE TITLE
Research/decide on contact us page

### ISSUE THREAD

**Issue by ntknguyen** [USEPA/cam-api-portal#52]
## Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)

## User Story
As a user
I want to easily contact someone for help/questions related to the CAM API portal
So that I can successfully use the CAM APIs

## Acceptance Criteria
Given a user clicks on a contact us button
When the page loads
Then they can either fill out a form or contact someone directly

Given a user fills out a form
When that form is submitted
Then this form sends an email to a shared mailbox that potentially creates a ticket

## Development Notes
Investigate what options are available and discuss what is necessary for the CAP API Portal

### Test Description
Verify that whatever action a user takes to contact us, we are notified and can respond

### Assumptions and Pre-Conditions
Assume the user clicks the button/link

### Test Data
Test account/email info to put into a form etc

### Steps to be Executed
1. Click the contact us button
2. Fill out form or get contact email
3. Verify we can receive this communication

## Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by j-tafoya** [comment]
https://www.epa.gov/airmarkets/cam-api-portal
