### ISSUE TITLE
Create content linking to CAM API Portal in CAMD web area

### ISSUE THREAD

**Issue by j-tafoya** [USEPA/cam-api-portal#67]
## Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)

## User Story
As a user visiting CAMD webpages
I want to see content about the CAM API with links
So that I can discover more data and ways to access them

## Acceptance Criteria
- [x] Modifications to [data resources page](https://www.epa.gov/airmarkets/data-resources)
  - [x] Modifications to [facility attributes page](https://www.epa.gov/airmarkets/facility-attributes)
  - [ ] Possible additions to [power plant emission trends page](https://www.epa.gov/airmarkets/power-plant-emission-trends)
  - [ ] Possible additions to [facility level comparisons page](https://www.epa.gov/airmarkets/facility-level-comparisons)
  - [ ] Possible additions to [power plant data viewer page](https://www.epa.gov/airmarkets/power-plant-data-viewer#Instructions)
  - [x] Modifications to [allowance data page](https://www.epa.gov/airmarkets/allowance-data)
  - [x] Modifications to [power sector data page](https://www.epa.gov/airmarkets/power-sector-emissions-data)
- [ ] Possibly link to CAM API portal from [CSAPR page](https://www.epa.gov/csapr)
- [x] Modifications to [basic information site map page](https://www.epa.gov/airmarkets/basic-information-site-map)
- [ ] Possibly link to CAM API portal from [what is emissions trading](https://www.epa.gov/emissions-trading-resources/what-emissions-trading)
- [ ] FAQs
  - [x] Modifications to [CAMD's Power Sector Emissions Data FAQs](https://www.epa.gov/airmarkets/camds-power-sector-emissions-data-faqs)
  - [x] Modifications to [Allowance FAQs](https://www.epa.gov/airmarkets/allowance-faqs)
  - [ ] Possibly link to CAM API portal from [re-engineering FAQs](https://www.epa.gov/airmarkets/frequent-questions-about-camd-re-engineering-effort)

### Test Description
Verify all links to the CAM API work appropriately

### Assumptions and Pre-Conditions
n/a

### Test Data
n/a

### Steps to be Executed
1. Visit each page in CAMD web area that reference CAM API 
2. Verify links take you to the CAM API portal

## Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] CAMPD links have been published in the epa.gov/airmarkets web area.

**Comment by j-tafoya** [comment]
Reference this [issue](https://github.com/USEPA/cam-api-portal/issues/44#issuecomment-1013136085) for locations to link to CAM API Portal as well as this [FAQ](https://www.epa.gov/airmarkets/frequent-questions-about-camd-re-engineering-effort)

**Comment by ibarra-michelle** [comment]
General CAM API description ⬇
- Clean Air Markets API (CAM API): these REST APIs allow you to access Clean Air Markets Program data directly from a data tool or your favorite programming language (Python, R, JavaScript, etc.).

**Comment by ibarra-michelle** [comment]
@ntknguyen - could you review the following Clean Air Markets API Portal (CAM API) text and links in Drupal?
- [ ] Modifications to [data resources page](https://www.epa.gov/airmarkets/data-resources)
  - [ ] Modifications to [facility attributes page](https://www.epa.gov/airmarkets/facility-attributes)
  - [ ] Modifications to [power sector data page](https://www.epa.gov/airmarkets/power-sector-emissions-data)
- [ ] Modifications to [basic information site map page](https://www.epa.gov/airmarkets/basic-information-site-map)
- FAQs
  - [ ] Modifications to [CAMD's Power Sector Emissions Data FAQs](https://www.epa.gov/airmarkets/camds-power-sector-emissions-data-faqs)
  - [ ] Modifications to [allowance data page](https://www.epa.gov/airmarkets/allowance-data)
  - [ ] Modifications to [Allowance FAQs](https://www.epa.gov/airmarkets/allowance-faqs)

**Comment by ntknguyen** [comment]
> @ntknguyen - could you review the following Clean Air Markets API Portal (CAM API) text and links in Drupal?
> 
> * [ ]  Modifications to [data resources page](https://www.epa.gov/airmarkets/data-resources)
-->   **I think for the consistency with Power sector data page the link to CAM API should be next to the link to AMPD.**
>   * [ ]  Modifications to [facility attributes page](https://www.epa.gov/airmarkets/facility-attributes)
--> **Same comment as the above.  I think we need to add CAM API  in the tables also.**
>  * [ ]  Modifications to [power sector data page](https://www.epa.gov/airmarkets/power-sector-emissions-data)  **--> This page looks good.**
> * [ ]  Modifications to [basic information site map page](https://www.epa.gov/airmarkets/basic-information-site-map) **--> This page looks good.**
> * FAQs
>   
>   * [ ]  Modifications to [CAMD's Power Sector Emissions Data FAQs] (https://www.epa.gov/airmarkets/camds-power-sector-emissions-data-faqs) 
>   * [ ]  Modifications to [allowance data page](https://www.epa.gov/airmarkets/allowance-data)
>   * [ ]  Modifications to [Allowance FAQs](https://www.epa.gov/airmarkets/allowance-faqs)
**--> These pages looks good.**

**Comment by ibarra-michelle** [comment]
Thx @ntknguyen. Please see the latest updates to:

**Comment by ibarra-michelle** [comment]
A new card has been create to review other possible links to the CAM API page in ticket #129 .

**Comment by ibarra-michelle** [comment]
The CAM API link have been published.
